### ISSUE TITLE
Getting a deprecation warning when installing

### ISSUE THREAD

**Issue by lenovouser** [1000ch/gulp-image#53]
![](https://i.lenovouser.me/SIZbssBbbIWTFCSH.jpg)

**Comment by 1000ch** [comment]
Fix by [v4.4.1](https://github.com/1000ch/gulp-image/releases/tag/v4.4.1).

**Comment by mcjwb** [comment]
Hi,
Sorry but this doesn't appear to be fixed by v4.4.1
![image](https://user-images.githubusercontent.com/2527867/52557809-729c0180-2de8-11e9-978c-f328bef7f5a3.png)
looks like you fixed it in [#858600f](https://github.com/1000ch/gulp-image/commit/858600f3d0f3579ab155a671c35fe83760369f0e) but a new npm release is needed.

If you have the time, are you able to publish a new version to npm?

Thanks for all your hard work on this package.
Best Regards,
Joe
